# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/e-bmaker"
    schedule:
      interval: "monthly" # Frecuencia con la que Dependabot buscará actualizaciones (semanalmente)

    labels:
      - "dependencies" # Añade una etiqueta a los PRs de Dependabot
    commit-message:
       prefix: "deps" # Prefijo para los mensajes de commit de Dependabot
       prefix-development: "deps-dev"
       include: "scope"
